export const usableOptions = [
  "Banquet",
  "Bar Mitzvah",
  "Bat Mitzvah",
  "Birthday Party",
  "Class Reunion",
  "Charity Event",
  "Family Reunion",
  "Fundraiser",
  "Graduation",
  "Holiday Party",
  "Private Party",
  "Prom",
  "Quinceanera",
  "School Dance",
  "Wedding",
  "Wedding Anniversary/Celebration",
  "Other",
];
