export const FULL_PRICE_PAYMENT_DISCOUNT_WHEN_MORE_THAN_60_DAYS = 0.05;
export const HOLD_PERCENTAGE = 0.5;

export const STRIPE_FIXED_FEE_IN_CENTS = 30;
export const STRIPE_PERCENTAGE_FEE = 0.029;
// export const EXPEDITED_EVENT_FEE_IN_CENTS = 200 * 100;
